//
//  Dimensions.h
//  Hockey Playoffs
//
//  Created by Pierre-Marc Airoldi on 2014-03-07.
//  Copyright (c) 2015 Pierre-Marc Airoldi. All rights reserved.
//

#define LINE_WIDTH 2
#define SIDE_MARGIN 10.0
#define TOP_MARGIN 10.0
#define BOTTOM_MARGIN 10.0
#define TOOLBAR_HEIGHT 49.0
#define STATUS_BAR_HEIGHT 20.0
#define MIN_SECTION_HEADER_HEIGHT 20.0
#define SERIES_STROKE_SIZE 1.5
#define CORNER_RADIUS 10
#define SERIES_NAME_FONT_SIZE 14.0
#define SERIES_WINS_FONT_SIZE 15.0
#define SERIES_NAME_MIN_FONT_SIZE 10.0
#define SERIES_WINS_MIN_FONT_SIZE 10.0
#define SERIES_GAME_LABEL_WIDTH 30.0
#define SCORE_SPACEING 1.0

#define TEAM_IMAGE_SIZE 50
#define TEAM_LABEL_WIDTH 100
#define TEAM_LABEL_FONT_SIZE 14
#define IMAGE_X_OFFSET 7
#define LABEL_X_OFFSET 9
#define STATUS_LABEL_FONT_SIZE 18

#define TIME_LABEL_FONT_SIZE 10
#define TEXT_LABEL_FONT_SIZE 14
#define DETAIL_GAME_X_OFFSET 5
#define DETAIL_GAME_Y_OFFSET 5

#define DETAIL_GAME_HEADER_FONT_SIZE 14
#define SCORE_LABEL_FONT_SIZE 35
#define DETAIL_GAME_STATUS_FONT_SIZE 16

#define SCORE_LABEL_WIDTH 30.0

#define PERIOD_SCORE_VIEW_HEIGHT 25.0
#define PERIOD_SCORE_VIEW_HEADER_HEIGHT 15.0
#define PERIOD_SCORE_VIEW_HEADER_FONT_SIZE 12
#define SECTION_CONTROL_HEIGHT 29.0

#define GAME_HEADER_SCORE_LABEL_WIDTH 35.0

#define VIDEO_BUTTON_WIDTH 30.0
#define VIDEO_BUTTON_HEIGHT 30.0

#define VIDEO_LINE_HEIGHT 2.0
#define SHOW_VIDEO_OFFSET 40.0

#define GAME_LABEL_FONT_SIZE 10.0