fastlane_version '2.88.0'

default_platform :ios

platform :ios do
  before_all do
    clean_build_artifacts
  end

  desc 'Runs all the tests'
  lane :test do
    scan(
      workspace: 'HockeyPlayoffs.xcworkspace',
      scheme: 'HockeyPlayoffsTests',
      device: 'iPhone 17 Pro (26.4)',
    )
  end

  desc 'Update metadata'
  lane :marketing do |options|
    overwrite_screenshots = false
    
    if options[:screenshots]
      snapshot
      overwrite_screenshots = true
    end

    deliver force: true, submit_for_review: false, skip_binary_upload: true, overwrite_screenshots: overwrite_screenshots
  end

  desc 'Builds app and packages it'
  private_lane :build do |options|
    snapshot if options[:screenshots]

    cert
    sigh
    gym scheme: 'HockeyPlayoffs'

    if options[:beta]
      deliver force: true, submit_for_review: false
    else
      deliver force: true, submit_for_review: true
    end

    clean_build_artifacts
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  lane :beta do |options|
    increment_build_number
    build(beta: true, screenshots: options[:screenshots])
  end

  desc 'Deploy a new version to the App Store'
  lane :deploy do |options|
    build(screenshots: options[:screenshots])
  end
end
