fastlane_version '2.88.0'

default_platform :ios

platform :ios do
  before_all do
    clean_build_artifacts
  end

  desc 'Runs all the tests'
  lane :test do
    scan(
      workspace: 'HockeyPlayoffs.xcworkspace',
      device: 'iPhone 17 Pro (26.2)',
      scheme: 'HockeyPlayoffsTests'
    )
  end

  desc 'Builds app and packages it'
  private_lane :build do |options|
    snapshot if options[:screenshots]

    match(readonly: true)
    build_app(scheme: "HockeyPlayoffs", xcargs: "-allowProvisioningUpdates")

    if options[:beta]
      deliver(force: true, submit_for_review: false)
    else
      deliver(force: true, submit_for_review: true)
    end

    clean_build_artifacts
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  lane :beta do |options|
    increment_build_number
    build(beta: true, screenshots: options[:screenshots])
  end

  desc 'Deploy a new version to the App Store'
  lane :deploy do |options|
    build(screenshots: options[:screenshots])
  end
end
