# A list of devices you want to take the screenshots from
devices([
  'iPhone 6',
  'iPhone 6 Plus',
  'iPhone 5',
  'iPhone 4s'
])

languages([
  'en-US'
])

# Where should the resulting screenshots be stored?
screenshots_path './screenshots'

clear_previous_screenshots # remove the '#'' to clear all previously generated screenshots before creating new ones

# The name of the project's scheme
scheme 'HockeyPlayoffs'
