ios_version '26.4'
skip_open_summary true,

# A list of devices you want to take the screenshots from
devices([
  # 'iPhone 14',
  # 'iPhone 14 Plus',
  'iPhone 17 Pro',
  'iPhone 17 Pro Max'
])

languages([
  'en-US'
])

# The name of the scheme which contains the UI Tests
scheme('Screenshots')

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(['-date "2025-05-01 00:00:00"'])

# For more information about all available options run
# fastlane action snapshot
