//
//  Colours.h
//  Hockey Playoffs
//
//  Created by Pierre-Marc Airoldi on 2014-03-07.
//  Copyright (c) 2015 Pierre-Marc Airoldi. All rights reserved.
//

#define colorComponent(x) x/255.0

#define TINT_COLOUR [UIColor colorWithRed:colorComponent(0) green:colorComponent(122) blue:colorComponent(255) alpha:1.0]

#define DARK_GRAY_COLOUR [UIColor colorWithRed:colorComponent(51) green:colorComponent(51) blue:colorComponent(51) alpha:1.0]
#define LIGHT_GRAY_COLOUR [UIColor colorWithRed:colorComponent(92) green:colorComponent(92) blue:colorComponent(92) alpha:1.0]
#define WHITE_COLOUR [UIColor whiteColor]
#define ULTRA_LIGHT_GRAY_COLOUR [UIColor colorWithRed:colorComponent(220) green:colorComponent(220) blue:colorComponent(220) alpha:1.0]

#define BACKGROUND_COLOUR DARK_GRAY_COLOUR

#define SERIES_BACKGROUND_COLOUR WHITE_COLOUR
#define SERIES_BORDER_COLOUR WHITE_COLOUR
#define SERIES_BORDER_TODAY_COLOUR TINT_COLOUR

#define SERIES_SELECTED_COLOUR [UIColor colorWithWhite:0.7 alpha:0.7]

#define BRACKET_LINE_COLOUR WHITE_COLOUR

#define SERIES_TEAM_NAME_COLOUR WHITE_COLOUR
#define SERIES_WINS_COLOUR WHITE_COLOUR

#define SERIES_HEADER_BACKGROUND_COLOUR WHITE_COLOUR

#define GAME_BACKGROUND_COLOUR WHITE_COLOUR

#define GAME_CELL_STATUS_TEXT_COLOUR DARK_GRAY_COLOUR
#define GAME_CELL_TEAM_TEXT_COLOUR LIGHT_GRAY_COLOUR

#define TABLE_VIEW_SEPERATOR_COLOUR ULTRA_LIGHT_GRAY_COLOUR

#define NAVIGATION_BAR_COLOUR [UIColor whiteColor]

#define GAME_DETAIL_CELL_TEXT_COLOUR DARK_GRAY_COLOUR
#define GAME_DETAIL_CELL_TIME_COLOUR LIGHT_GRAY_COLOUR

#define GAME_DETAIL_HEADER_TEXT_COLOUR DARK_GRAY_COLOUR
#define GAME_DETAIL_HEADER_BACKGROUND_COLOUR ULTRA_LIGHT_GRAY_COLOUR

#define GAME_CELL_SCORE_COLOUR DARK_GRAY_COLOUR
#define PERIOD_SCORE_BACKGROUND_COLOUR DARK_GRAY_COLOUR
#define PERIOD_SCORE_SEPERATOR_COLOUR WHITE_COLOUR

#define SEGMENT_BACKGROUND_COLOUR [UIColor clearColor]
#define SEGEMENT_TINT_COLOUR TINT_COLOUR
#define PERIOD_SCORE_VIEW_HEADER_FONT_COLOUR LIGHT_GRAY_COLOUR

#define VIDEO_BUTTON_DISABLED_COLOUR ULTRA_LIGHT_GRAY_COLOUR
#define VIDEO_BUTTON_UNSELECTED_COLOUR TINT_COLOUR
#define VIDEO_BUTTON_SELECTED_COLOUR LIGHT_GRAY_COLOUR

#define SERIES_CELL_BACKGROUND_COLOUR [UIColor colorWithRed:colorComponent(200) green:colorComponent(200) blue:colorComponent(200) alpha:1.0]

#define EXPANDED_VIDEO_BACKGROUND_COLOUR WHITE_COLOUR
#define GAME_LABEL_TEXT_COLOUR LIGHT_GRAY_COLOUR
